name: PySpark-Dev

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted
    steps:
      #----------------------------------------------
      #       check-out repo
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
      #----------------------------------------------
      # install your root project, if required
      #----------------------------------------------
      - name: Install library
        run: poetry install
      #----------------------------------------------
      # run tests
      #----------------------------------------------
      - name: Run PyTest
        run: poetry run pytest tests/ 
