name: PySpark-Dev

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted
    steps:
      #----------------------------------------------
      #       check-out repo
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
      #----------------------------------------------
      # install your root project, if required
      #----------------------------------------------
      - name: Install library
        run: poetry install
      #----------------------------------------------
      # run tests
      #----------------------------------------------
      - name: Run PyTest
        run: poetry run pytest tests/ --junitxml=test-results/out_report.xml
        
      #----------------------------------------------
      # display test results
      #---------------------------------------------- 
      
#      - name: Publish Unit Test Results
#        uses: EnricoMi/publish-unit-test-result-action/composite@v1.32
#        with:
#          files: "test-results/**/*.xml"
      
      
      - name: FOSSA Scan
        run: FOSSA_API_KEY=454effbebe694b924ad17226cf329210 fossa analyze

